version: '3.9'

services:
  nestapp:
    container_name: testnestapp
    image: testnestapp:1.0.0
    build:
      context: .
    ports:
    - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - backend_network
    environment:
      - PORT=${PORT}
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres
    container_name: db
    ports:
    - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    networks:
      - backend_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: redis-db
    env_file:
      - .env
    networks:
      - backend_network
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    volumes:
      - redisdata:/data

networks:
  backend_network:
    driver: bridge

volumes:
  redisdata: 
    driver: local
  pgdata: {}